services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
